apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: taskflow-backend
    environment: {{ .Values.environment }}
    backstage.io/kubernetes-id: taskflow-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: taskflow-backend
  template:
    metadata:
      labels:
        app: taskflow-backend
        environment: {{ .Values.environment }}
        backstage.io/kubernetes-id: taskflow-app
    spec:
      containers:
        - name: taskflow-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.backendPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.backendPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.backendPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: taskflow-frontend
    environment: {{ .Values.environment }}
    backstage.io/kubernetes-id: taskflow-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: taskflow-frontend
  template:
    metadata:
      labels:
        app: taskflow-frontend
        environment: {{ .Values.environment }}
        backstage.io/kubernetes-id: taskflow-app
    spec:
      containers:
        - name: taskflow-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.frontendPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}