apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform components — Backstage IDP and supporting tooling
  sourceRepos:
    - https://github.com/OnyiGlobal2025/taskflow-backstage
  destinations:
    - namespace: backstage
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'