replicaCount: 3

image:
  tag: "08171748865bd3e96ebc140f0d6e084314777fbe"

namespace: taskflow-prod
environment: prod

ingress:
  enabled: true
  host: taskflow.okorojeremiah.online

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70