replicaCount: 1

backend:
  image:
    repository: 713923090919.dkr.ecr.us-east-1.amazonaws.com/taskflow
    tag: "backend-a18b47d2887e2996ba78e339f3897b6b1b57ca74"

frontend:
  image:
    repository: 713923090919.dkr.ecr.us-east-1.amazonaws.com/taskflow
    tag: "backend-a18b47d2887e2996ba78e339f3897b6b1b57ca74"

namespace: taskflow-prod
environment: prod

ingress:
  enabled: true
  host: taskflow.okorojeremiah.online

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false