replicaCount: 3

image:
  repository: 713923090919.dkr.ecr.us-east-1.amazonaws.com/taskflow
  tag: "backend-a754f47fa272ec289cf99abbf9c3bd3112b23267"

namespace: taskflow-prod
environment: prod

ingress:
  enabled: true
  host: taskflow.okorojeremiah.online

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70