replicaCount: 1

image:
  repository: 713923090919.dkr.ecr.us-east-1.amazonaws.com/taskflow
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  backendPort: 5000
  frontendPort: 80

ingress:
  enabled: true
  host: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

namespace: default
environment: dev