replicaCount: 2

image:
  tag: "638f1324bd13543f4d80fd60e3f5ea4afb7fd15f"

namespace: taskflow-staging
environment: staging

ingress:
  enabled: true
  host: staging.taskflow.okorojeremiah.online

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70