replicaCount: 1

backend:
  image:
    repository: 713923090919.dkr.ecr.us-east-1.amazonaws.com/taskflow
    tag: "backend-1dedae99d7a34775e2585661d7cbcbd4eebcbc46"

frontend:
  image:
    repository: 713923090919.dkr.ecr.us-east-1.amazonaws.com/taskflow
    tag: "backend-1dedae99d7a34775e2585661d7cbcbd4eebcbc46"

namespace: taskflow-staging
environment: staging

ingress:
  enabled: true
  host: staging-taskflow.okorojeremiah.online

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false