replicaCount: 2

image:
  tag: "a6c6c62c34fb0165d68665c3bc577339fb28318c"

namespace: taskflow-staging
environment: staging

ingress:
  enabled: true
  host: staging.taskflow.okorojeremiah.online

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70