replicaCount: 1

image:
  tag: "a6c6c62c34fb0165d68665c3bc577339fb28318c"

namespace: taskflow-dev
environment: dev

ingress:
  enabled: true
  host: dev.taskflow.okorojeremiah.online

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false