replicaCount: 1

image:
  tag: "638f1324bd13543f4d80fd60e3f5ea4afb7fd15f"

namespace: taskflow-dev
environment: dev

ingress:
  enabled: true
  host: dev.taskflow.okorojeremiah.online

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false