replicaCount: 1

backend:
  image:
    repository: 713923090919.dkr.ecr.us-east-1.amazonaws.com/taskflow
    tag: "backend-77a5ad862f1f0fac3f7ecf0340aed4c71d55ebf5"

frontend:
  image:
    repository: 713923090919.dkr.ecr.us-east-1.amazonaws.com/taskflow
    tag: "backend-77a5ad862f1f0fac3f7ecf0340aed4c71d55ebf5"

namespace: taskflow-dev
environment: dev

ingress:
  enabled: true
  host: dev-taskflow.okorojeremiah.online

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false